import { AlertTriangle, ArrowLeftRight, ArrowRight, Plus, Search } from "lucide-react";
import Link from "next/link";

import { PageHeader } from "@/components/layout/page-header";
import { requireStore } from "@/features/catalog/server/store-context";
import { findSalesForExchange, getExchanges } from "@/features/exchanges/queries/exchanges";

const currency = new Intl.NumberFormat("pt-BR", { style: "currency", currency: "BRL" });

export default async function ExchangesPage({ searchParams }: { searchParams: Promise<{ busca?: string }> }) {
  const { store } = await requireStore();
  const params = await searchParams;
  const query = typeof params.busca === "string" ? params.busca : "";
  const [sales, history] = store ? await Promise.all([findSalesForExchange(store.id, query), getExchanges(store.id)]) : [[], []];
  return <><PageHeader title="Trocas" description="Localize a venda original e registre a entrada e saída dos produtos." action={<Link href="/trocas/nova" className="ui-button-primary"><Plus size={18} /> Nova troca</Link>} />
    <section className="ui-card mb-6 p-5"><div className="flex items-center gap-3"><span className="grid size-9 place-items-center rounded-lg bg-brand-subtle text-brand-deep"><Search size={18} /></span><div><h2 className="font-semibold">Buscar venda para troca</h2><p className="text-xs text-muted">Número da venda, nome ou telefone da cliente</p></div></div><form className="mt-4 flex flex-col gap-3 sm:flex-row"><input name="busca" defaultValue={query} className="ui-input" placeholder="Ex.: SM-20260812 ou Maria" /><button className="ui-button-secondary shrink-0">Buscar venda</button></form>{query ? <div className="mt-4 grid gap-2">{sales.length ? sales.map((sale) => <Link key={sale.id} href={`/trocas/nova?venda=${sale.id}`} className="flex items-center justify-between gap-3 rounded-xl border border-border p-4 hover:border-brand"><div><p className="text-sm font-semibold">{sale.number}</p><p className="text-xs text-muted">{sale.customerName || "Cliente não identificada"} · {sale.soldAt.toLocaleDateString("pt-BR")}</p></div><div className="flex items-center gap-3"><strong className="text-sm">{currency.format(Number(sale.totalAmount))}</strong><ArrowRight size={17} className="text-brand-deep" /></div></Link>) : <p className="py-5 text-center text-sm text-muted">Nenhuma venda confirmada encontrada.</p>}</div> : null}</section>
    <section className="ui-card overflow-hidden"><div className="border-b border-border px-5 py-4"><h2 className="font-semibold">Histórico de trocas</h2><p className="mt-1 text-xs text-muted">Registros mais recentes</p></div>{history.length ? <div className="overflow-x-auto"><table className="w-full min-w-[780px] text-left text-sm"><thead className="bg-background text-xs uppercase tracking-wide text-muted"><tr><th className="px-5 py-4">Troca</th><th className="px-4 py-4">Venda / cliente</th><th className="px-4 py-4">Motivo</th><th className="px-4 py-4">Diferença</th><th className="px-5 py-4 text-right">Detalhes</th></tr></thead><tbody className="divide-y divide-border">{history.map((exchange) => <tr key={exchange.id}><td className="px-5 py-4"><p className="font-semibold">{exchange.exchangedAt.toLocaleDateString("pt-BR")}</p>{exchange.outsideDeadline ? <p className="mt-1 flex items-center gap-1 text-xs font-semibold text-amber-700"><AlertTriangle size={13} /> Fora do prazo</p> : <p className="mt-1 text-xs text-success-strong">Dentro do prazo</p>}</td><td className="px-4 py-4"><p>{exchange.saleNumber}</p><p className="text-xs text-muted">{exchange.customerName || "Sem cliente"}</p></td><td className="px-4 py-4">{exchange.reason}</td><td className="px-4 py-4 font-semibold">{currency.format(Number(exchange.differenceAmount))}</td><td className="px-5 py-4"><Link href={`/trocas/${exchange.id}`} className="ml-auto flex w-fit items-center gap-1 font-semibold text-brand-deep">Abrir <ArrowRight size={16} /></Link></td></tr>)}</tbody></table></div> : <div className="px-6 py-14 text-center"><ArrowLeftRight className="mx-auto text-muted-soft" size={30} /><h3 className="mt-4 font-semibold">Nenhuma troca registrada</h3><p className="mt-1 text-sm text-muted">Use a busca acima para iniciar a primeira.</p></div>}</section>
  </>;
}
