import { Banknote, Boxes, Download, HandCoins, ShoppingBag } from "lucide-react";
import Link from "next/link";

import { PageHeader } from "@/components/layout/page-header";
import { requireStore } from "@/features/catalog/server/store-context";
import { getReportsData, normalizeReportRange, type ReportType } from "@/features/reports/queries/reports";

const currency = new Intl.NumberFormat("pt-BR", { style: "currency", currency: "BRL" });
const tabs: Array<{ id: ReportType; label: string; icon: typeof ShoppingBag }> = [{ id: "sales", label: "Vendas", icon: ShoppingBag }, { id: "inventory", label: "Estoque", icon: Boxes }, { id: "cash", label: "Caixa", icon: Banknote }, { id: "receivables", label: "Fiado", icon: HandCoins }];
const paymentLabels: Record<string, string> = { cash: "Dinheiro", pix: "Pix", debit_card: "Débito", credit_card: "Crédito", on_account: "Fiado" };
const movementLabels: Record<string, string> = { initial: "Estoque inicial", entry: "Entradas", sale: "Saídas por venda", sale_cancellation: "Cancelamentos", exchange_in: "Entradas por troca", exchange_out: "Saídas por troca", adjustment_in: "Ajustes de entrada", adjustment_out: "Ajustes de saída", damaged: "Danificados" };

export default async function ReportsPage({ searchParams }: { searchParams: Promise<{ tipo?: string; inicio?: string; fim?: string }> }) {
  const { store } = await requireStore();
  const params = await searchParams;
  const type: ReportType = tabs.some((tab) => tab.id === params.tipo) ? params.tipo as ReportType : "sales";
  const range = normalizeReportRange(params.inicio, params.fim);
  const data = store ? await getReportsData(store.id, range.from, range.to) : null;
  const query = `inicio=${range.from}&fim=${range.to}`;
  return <><PageHeader title="Relatórios" description="Acompanhe o desempenho da loja e exporte os dados do período." action={<a href={`/api/relatorios/${type}?${query}`} className="ui-button-secondary"><Download size={17} /> Exportar CSV</a>} />
    <form className="ui-card mb-5 grid gap-3 p-4 sm:grid-cols-[1fr_1fr_auto]"><input type="hidden" name="tipo" value={type} /><label><span className="text-xs font-semibold text-muted">Data inicial</span><input name="inicio" type="date" defaultValue={range.from} className="ui-input mt-1.5" /></label><label><span className="text-xs font-semibold text-muted">Data final</span><input name="fim" type="date" defaultValue={range.to} className="ui-input mt-1.5" /></label><button className="ui-button-primary self-end">Aplicar período</button></form>
    <nav className="mb-6 grid grid-cols-2 gap-2 rounded-xl border border-border bg-white p-2 sm:grid-cols-4" aria-label="Tipos de relatório">{tabs.map(({ id, label, icon: Icon }) => <Link key={id} href={`/relatorios?tipo=${id}&${query}`} className={type === id ? "flex min-h-11 items-center justify-center gap-2 rounded-lg bg-black px-3 text-sm font-semibold text-white" : "flex min-h-11 items-center justify-center gap-2 rounded-lg px-3 text-sm font-semibold text-muted hover:bg-background hover:text-foreground"}><Icon size={17} /> {label}</Link>)}</nav>
    {!data ? <p className="ui-card p-6 text-sm text-muted">Configure a loja para gerar relatórios.</p> : type === "sales" ? <SalesReport data={data.sales} /> : type === "inventory" ? <InventoryReport data={data.inventory} /> : type === "cash" ? <CashReport data={data.cash} /> : <ReceivablesReport data={data.receivables} />}
  </>;
}

function Stats({ items }: { items: Array<{ label: string; value: string; note?: string }> }) { return <section className="grid gap-4 sm:grid-cols-2 xl:grid-cols-4">{items.map((item) => <article key={item.label} className="ui-card p-5"><p className="text-xs font-semibold uppercase tracking-wide text-muted">{item.label}</p><strong className="mt-3 block text-2xl">{item.value}</strong>{item.note ? <p className="mt-1 text-xs text-muted">{item.note}</p> : null}</article>)}</section>; }
function SimpleTable({ title, headers, rows }: { title: string; headers: string[]; rows: Array<Array<React.ReactNode>> }) { return <article className="ui-card overflow-hidden"><div className="border-b border-border px-5 py-4"><h2 className="font-semibold">{title}</h2></div>{rows.length ? <div className="overflow-x-auto"><table className="w-full min-w-[560px] text-left text-sm"><thead className="bg-background text-xs uppercase tracking-wide text-muted"><tr>{headers.map((header) => <th key={header} className="px-5 py-3">{header}</th>)}</tr></thead><tbody className="divide-y divide-border">{rows.map((row, index) => <tr key={index}>{row.map((cell, cellIndex) => <td key={cellIndex} className="px-5 py-4">{cell}</td>)}</tr>)}</tbody></table></div> : <p className="px-5 py-10 text-center text-sm text-muted">Sem dados no período.</p>}</article>; }

function SalesReport({ data }: { data: Awaited<ReturnType<typeof getReportsData>>["sales"] }) { return <div className="space-y-6"><Stats items={[{ label: "Total vendido", value: currency.format(Number(data.summary.revenue)) }, { label: "Vendas", value: String(data.summary.saleCount) }, { label: "Peças", value: String(data.summary.pieces) }, { label: "Ticket médio", value: currency.format(Number(data.summary.ticketAverage)) }]} /><section className="grid gap-6 xl:grid-cols-2"><SimpleTable title="Produtos mais vendidos" headers={["Produto", "Peças", "Receita"]} rows={data.products.map((row) => [row.name, row.pieces, currency.format(Number(row.revenue))])} /><SimpleTable title="Vendas por origem" headers={["Origem", "Vendas", "Total"]} rows={data.bySource.map((row) => [row.label, row.count, currency.format(Number(row.value))])} /><SimpleTable title="Valores por pagamento" headers={["Forma", "Total"]} rows={data.byPayment.map((row) => [paymentLabels[row.label] ?? row.label, currency.format(Number(row.value))])} /></section></div>; }
function InventoryReport({ data }: { data: Awaited<ReturnType<typeof getReportsData>>["inventory"] }) { return <div className="space-y-6"><Stats items={[{ label: "Unidades em estoque", value: String(data.summary.units) }, { label: "Valor de custo", value: currency.format(Number(data.summary.costValue)) }, { label: "Estoque baixo", value: String(data.summary.lowCount) }, { label: "Esgotadas", value: String(data.summary.outCount) }]} /><section className="grid gap-6 xl:grid-cols-2"><SimpleTable title="Saldo por produto" headers={["Produto", "Categoria", "Saldo"]} rows={data.products.map((row) => [row.name, row.category ?? "—", <strong key={row.name} className={row.units <= row.minimum ? "text-amber-700" : ""}>{row.units}</strong>])} /><SimpleTable title="Movimentações no período" headers={["Tipo", "Quantidade"]} rows={data.movements.map((row) => [movementLabels[row.type] ?? row.type, row.quantity])} /></section></div>; }
function CashReport({ data }: { data: Awaited<ReturnType<typeof getReportsData>>["cash"] }) { return <div className="space-y-6"><Stats items={[{ label: "Valores recebidos", value: currency.format(Number(data.summary.received)) }, { label: "Sangrias", value: currency.format(Number(data.summary.withdrawals)) }, { label: "Despesas", value: currency.format(Number(data.summary.expenses)) }, { label: "Diferenças de caixa", value: currency.format(Number(data.closed.difference)), note: `${data.closed.count} fechamento(s)` }]} /><SimpleTable title="Recebimentos por forma de pagamento" headers={["Forma", "Total"]} rows={data.byPayment.map((row) => [paymentLabels[row.label ?? ""] ?? row.label ?? "Outros", currency.format(Number(row.value))])} /></div>; }
function ReceivablesReport({ data }: { data: Awaited<ReturnType<typeof getReportsData>>["receivables"] }) { return <div className="space-y-6"><Stats items={[{ label: "Total em aberto", value: currency.format(Number(data.summary.openAmount)) }, { label: "Total vencido", value: currency.format(Number(data.summary.overdueAmount)), note: `${data.summary.overdueCount} conta(s)` }, { label: "Recebido no período", value: currency.format(Number(data.received.received)) }, { label: "Pagamentos", value: String(data.received.count) }]} /><section className="grid gap-6 xl:grid-cols-2"><SimpleTable title="Maiores saldos" headers={["Cliente", "Telefone", "Saldo"]} rows={data.customers.map((row) => [<Link key={row.id} href={`/clientes/${row.id}`} className="font-semibold text-brand-deep">{row.name}</Link>, row.phone, currency.format(Number(row.balance))])} /><SimpleTable title="Pagamentos no período" headers={["Cliente", "Forma", "Valor", "Data"]} rows={data.payments.map((row) => [row.customerName, paymentLabels[row.method] ?? row.method, currency.format(Number(row.amount)), row.paidAt.toLocaleDateString("pt-BR")])} /></section></div>; }
