import { ArrowLeft, CalendarClock, Edit3, MessageCircle, ReceiptText, ShoppingBag } from "lucide-react";
import Link from "next/link";
import { notFound } from "next/navigation";

import { PageHeader } from "@/components/layout/page-header";
import { getOpenCashSession } from "@/features/cash/queries/cash";
import { requireStore } from "@/features/catalog/server/store-context";
import { ReceivablePaymentForm } from "@/features/customers/components/receivable-payment-form";
import { getCustomerDetails } from "@/features/customers/queries/customers";

const currency = new Intl.NumberFormat("pt-BR", { style: "currency", currency: "BRL" });
const paymentLabels: Record<string, string> = { cash: "Dinheiro", pix: "Pix", debit_card: "Débito", credit_card: "Crédito" };

function localToday() {
  return new Intl.DateTimeFormat("en-CA", { timeZone: "America/Sao_Paulo", year: "numeric", month: "2-digit", day: "2-digit" }).format(new Date());
}

export default async function CustomerDetailsPage({ params }: { params: Promise<{ id: string }> }) {
  const { store } = await requireStore();
  if (!store) notFound();
  const { id } = await params;
  const [result, cash] = await Promise.all([getCustomerDetails(store.id, id), getOpenCashSession(store.id)]);
  if (!result) notFound();
  const { customer, sales, receivables, payments, exchanges } = result;
  const openBalance = receivables.filter((item) => item.status !== "cancelled").reduce((sum, item) => sum + Number(item.remainingAmount), 0);
  const paidTotal = receivables.reduce((sum, item) => sum + Number(item.paidAmount), 0);
  const phone = customer.phone.replace(/\D/g, "");
  const whatsappPhone = phone.startsWith("55") ? phone : `55${phone}`;
  const message = encodeURIComponent(`Olá, ${customer.name}! Tudo bem? Passando para lembrar que há um saldo de ${currency.format(openBalance)} em aberto na Sir Modas. Se precisar, podemos combinar a melhor forma de pagamento.`);
  const today = localToday();

  return <>
    <PageHeader title={customer.name} description={`${customer.phone}${customer.birthDate ? ` · aniversário ${customer.birthDate.toLocaleDateString("pt-BR")}` : ""}`} action={<div className="flex flex-wrap gap-2"><Link href="/clientes" className="ui-button-secondary"><ArrowLeft size={17} /> Clientes</Link><Link href={`/clientes/${customer.id}/editar`} className="ui-button-secondary"><Edit3 size={17} /> Editar</Link>{phone ? <a href={`https://wa.me/${whatsappPhone}?text=${message}`} target="_blank" rel="noreferrer" className="ui-button-primary"><MessageCircle size={17} /> WhatsApp</a> : null}</div>} />
    <section className="mb-6 grid gap-4 sm:grid-cols-3"><article className="ui-card p-5"><p className="text-xs font-semibold uppercase tracking-wide text-muted">Total comprado</p><strong className="mt-2 block text-2xl">{currency.format(sales.filter((sale) => sale.status === "confirmed").reduce((sum, sale) => sum + Number(sale.totalAmount), 0))}</strong><p className="mt-1 text-xs text-muted">{sales.filter((sale) => sale.status === "confirmed").length} compra(s)</p></article><article className="ui-card p-5"><p className="text-xs font-semibold uppercase tracking-wide text-muted">Saldo em aberto</p><strong className={openBalance ? "mt-2 block text-2xl text-amber-700" : "mt-2 block text-2xl text-success-strong"}>{currency.format(openBalance)}</strong><p className="mt-1 text-xs text-muted">Valores ainda não recebidos</p></article><article className="ui-card p-5"><p className="text-xs font-semibold uppercase tracking-wide text-muted">Já recebido</p><strong className="mt-2 block text-2xl">{currency.format(paidTotal)}</strong><p className="mt-1 text-xs text-muted">Pagamentos de vendas fiadas</p></article></section>
    <section className="grid gap-6 xl:grid-cols-[1.2fr_0.8fr]">
      <div className="space-y-6"><article className="ui-card overflow-hidden"><div className="flex items-center gap-3 border-b border-border px-5 py-4"><span className="grid size-9 place-items-center rounded-lg bg-brand-subtle text-brand-deep"><ReceiptText size={18} /></span><div><h2 className="font-semibold">Contas no fiado</h2><p className="text-xs text-muted">Baixas integrais ou parciais</p></div></div>{receivables.length ? <div className="divide-y divide-border">{receivables.map((account) => { const overdue = account.status !== "paid" && account.status !== "cancelled" && account.remainingAmount !== "0.00" && account.dueDate < today; const accountPayments = payments.filter((payment) => payment.receivableId === account.id); return <div key={account.id} className="p-5"><div className="flex flex-wrap items-start justify-between gap-3"><div><Link href={`/vendas/${account.saleId}`} className="font-semibold hover:underline">{account.saleNumber}</Link><p className="mt-1 flex items-center gap-1 text-xs text-muted"><CalendarClock size={14} /> Vencimento {new Date(`${account.dueDate}T12:00:00`).toLocaleDateString("pt-BR")}</p></div><div className="text-right"><strong className={overdue ? "text-red-700" : account.status === "paid" ? "text-success-strong" : "text-amber-700"}>{currency.format(Number(account.remainingAmount))} em aberto</strong><p className="text-xs text-muted">de {currency.format(Number(account.originalAmount))}</p></div></div>{overdue ? <p className="mt-3 rounded-lg bg-red-50 px-3 py-2 text-xs font-semibold text-red-700">Pagamento vencido</p> : null}{accountPayments.length ? <div className="mt-4 space-y-2 border-l-2 border-brand-soft pl-3">{accountPayments.map((payment) => <p key={payment.id} className="text-xs text-muted"><strong className="text-foreground">{currency.format(Number(payment.amount))}</strong> recebido via {paymentLabels[payment.method]} em {payment.paidAt.toLocaleString("pt-BR")}</p>)}</div> : null}{account.status !== "paid" && account.status !== "cancelled" && Number(account.remainingAmount) > 0 ? <ReceivablePaymentForm receivableId={account.id} remainingAmount={account.remainingAmount} cashOpen={Boolean(cash)} /> : null}</div>; })}</div> : <div className="px-6 py-12 text-center text-sm text-muted">Nenhuma venda fiada para esta cliente.</div>}</article></div>
      <div className="space-y-6"><article className="ui-card overflow-hidden"><div className="flex items-center gap-3 border-b border-border px-5 py-4"><ShoppingBag size={18} className="text-brand-deep" /><h2 className="font-semibold">Histórico de compras</h2></div>{sales.length ? <ul className="divide-y divide-border">{sales.map((sale) => <li key={sale.id} className="flex items-center justify-between gap-3 px-5 py-4"><div><Link href={`/vendas/${sale.id}`} className="text-sm font-semibold hover:underline">{sale.number}</Link><p className="text-xs text-muted">{sale.soldAt.toLocaleDateString("pt-BR")} · {sale.source}</p></div><strong className={sale.status === "cancelled" ? "text-sm text-muted line-through" : "text-sm"}>{currency.format(Number(sale.totalAmount))}</strong></li>)}</ul> : <p className="px-5 py-10 text-center text-sm text-muted">Nenhuma compra vinculada.</p>}</article>{exchanges.length ? <article className="ui-card overflow-hidden"><div className="border-b border-border px-5 py-4"><h2 className="font-semibold">Histórico de trocas</h2></div><ul className="divide-y divide-border">{exchanges.map((exchange) => <li key={exchange.id} className="flex items-center justify-between gap-3 px-5 py-4"><div><Link href={`/trocas/${exchange.id}`} className="text-sm font-semibold text-brand-deep">{exchange.saleNumber}</Link><p className="text-xs text-muted">{exchange.reason} · {exchange.exchangedAt.toLocaleDateString("pt-BR")}</p></div><strong className="text-sm">{currency.format(Number(exchange.differenceAmount))}</strong></li>)}</ul></article> : null}<article className="ui-card p-5"><h2 className="font-semibold">Informações</h2><dl className="mt-4 space-y-3 text-sm"><div><dt className="text-xs font-semibold text-muted">Endereço</dt><dd className="mt-1">{customer.address || "Não informado"}</dd></div><div><dt className="text-xs font-semibold text-muted">Observações</dt><dd className="mt-1 leading-6">{customer.notes || "Nenhuma observação."}</dd></div></dl></article></div>
    </section>
  </>;
}
