import { AlertTriangle, ArrowRight, Boxes, CircleCheck, CircleDollarSign, HandCoins, PackagePlus, ShoppingBag, WalletCards } from "lucide-react";
import Link from "next/link";

import { PageHeader } from "@/components/layout/page-header";
import { requireStore } from "@/features/catalog/server/store-context";
import { getDashboardData } from "@/features/dashboard/queries/dashboard";

const currency = new Intl.NumberFormat("pt-BR", { style: "currency", currency: "BRL" });

export default async function DashboardPage({ searchParams }: { searchParams: Promise<{ periodo?: string }> }) {
  const { store } = await requireStore();
  const params = await searchParams;
  const period = params.periodo === "week" || params.periodo === "month" ? params.periodo : "today";
  const periodLabel = period === "month" ? "no mês" : period === "week" ? "na semana" : "hoje";
  const data = store ? await getDashboardData(store.id, period) : null;
  const revenue = Number(data?.sales.revenue ?? 0);
  const saleCount = data?.sales.saleCount ?? 0;
  const indicators = [
    { label: `Vendido ${periodLabel}`, value: currency.format(revenue), note: saleCount ? "Vendas confirmadas" : "Nenhuma venda registrada", icon: CircleDollarSign, tone: "brand" },
    { label: "Vendas", value: String(saleCount), note: saleCount === 1 ? `1 venda ${periodLabel}` : `${saleCount} vendas ${periodLabel}`, icon: ShoppingBag, tone: "neutral" },
    { label: "Estoque baixo", value: String(data?.stock.lowCount ?? 0), note: data?.stock.outCount ? `${data.stock.outCount} variação(ões) esgotada(s)` : "Sem itens esgotados", icon: AlertTriangle, tone: "warning" },
    { label: "Fiado em aberto", value: currency.format(Number(data?.receivables.openAmount ?? 0)), note: data?.receivables.overdueCount ? `${currency.format(Number(data.receivables.overdueAmount))} vencido em ${data.receivables.overdueCount} conta(s)` : "Nenhuma conta vencida", icon: HandCoins, tone: data?.receivables.overdueCount ? "warning" : "success" },
  ];
  const attentionItems = [
    data?.stock.outCount ? { href: "/estoque?status=out", text: `${data.stock.outCount} produto${data.stock.outCount === 1 ? "" : "s"} esgotado${data.stock.outCount === 1 ? "" : "s"}` } : null,
    data?.stock.lowCount ? { href: "/estoque?status=low", text: `${data.stock.lowCount} produto${data.stock.lowCount === 1 ? "" : "s"} com estoque baixo` } : null,
    data?.receivables.overdueCount ? { href: "/clientes", text: `${data.receivables.overdueCount} conta${data.receivables.overdueCount === 1 ? "" : "s"} vencida${data.receivables.overdueCount === 1 ? "" : "s"}` } : null,
  ].filter((item): item is { href: string; text: string } => item !== null);
  const quickActions = [
    { href: "/vendas/nova", title: "Registrar venda", description: "Escolha os produtos e finalize a venda.", icon: ShoppingBag, primary: true },
    { href: "/produtos/novo", title: "Cadastrar produto", description: "Adicione uma peça nova ao catálogo.", icon: PackagePlus, primary: false },
    { href: "/estoque", title: "Ver estoque", description: "Confira o que está disponível na loja.", icon: Boxes, primary: false },
  ];
  return <><PageHeader title="Olá! O que você quer fazer?" description="Use um dos atalhos abaixo ou acompanhe como a loja está." />
    <section className="mb-6" aria-labelledby="quick-actions-title"><div className="mb-3"><h2 id="quick-actions-title" className="text-lg font-bold">Ações principais</h2><p className="mt-1 text-sm text-muted">As tarefas mais usadas no dia a dia.</p></div><div className="grid gap-3 sm:grid-cols-3">{quickActions.map(({ href, title, description, icon: Icon, primary }) => <Link key={href} href={href} className={primary ? "group rounded-xl bg-black p-5 text-white shadow-sm transition hover:bg-[#1a1a1a] focus-visible:outline-white" : "ui-card group p-5 transition hover:border-brand hover:bg-[#fff9f8]"}><span className={primary ? "grid size-10 place-items-center rounded-lg bg-white/15" : "grid size-10 place-items-center rounded-lg bg-brand-subtle text-brand-deep"}><Icon size={20} /></span><h3 className="mt-5 font-bold">{title}</h3><p className={primary ? "mt-1 text-sm leading-5 text-white/75" : "mt-1 text-sm leading-5 text-muted"}>{description}</p><span className={primary ? "mt-5 inline-flex items-center gap-1 text-sm font-semibold" : "mt-5 inline-flex items-center gap-1 text-sm font-semibold text-brand-deep"}>Abrir <ArrowRight size={16} className="transition-transform group-hover:translate-x-0.5" /></span></Link>)}</div></section>
    <section className={attentionItems.length ? "mb-6 rounded-xl border border-amber-200 bg-amber-50 px-5 py-4" : "mb-6 rounded-xl border border-[#b9e5d0] bg-[#effaf4] px-5 py-4"} aria-live="polite"><div className="flex items-start gap-3">{attentionItems.length ? <AlertTriangle className="mt-0.5 shrink-0 text-amber-700" size={20} /> : <CircleCheck className="mt-0.5 shrink-0 text-success-strong" size={20} />}<div><h2 className="font-semibold">{attentionItems.length ? "Atenção para hoje" : "Tudo organizado por enquanto"}</h2>{attentionItems.length ? <div className="mt-2 flex flex-wrap gap-x-4 gap-y-2">{attentionItems.map((item) => <Link key={item.href} href={item.href} className="text-sm font-semibold text-amber-800 underline decoration-amber-300 underline-offset-2 hover:text-amber-950">{item.text}</Link>)}</div> : <p className="mt-1 text-sm text-muted">Não há produtos com estoque baixo ou contas vencidas.</p>}</div></div></section>
    <nav className="mb-5 flex w-fit rounded-xl border border-border bg-white p-1" aria-label="Período do dashboard">{[["today", "Hoje"], ["week", "Semana"], ["month", "Mês"]].map(([id, label]) => <Link key={id} href={`/inicio?periodo=${id}`} className={period === id ? "rounded-lg bg-black px-4 py-2 text-sm font-semibold text-white" : "rounded-lg px-4 py-2 text-sm font-semibold text-muted hover:text-foreground"}>{label}</Link>)}</nav>
    <section className="grid gap-4 sm:grid-cols-2 xl:grid-cols-4" aria-label="Indicadores do dia">{indicators.map(({ label, value, note, icon: Icon, tone }) => <article key={label} className="ui-card p-5"><div className="flex items-center justify-between"><p className="text-sm font-medium text-muted">{label}</p><span className={`grid size-9 place-items-center rounded-lg ${tone === "brand" ? "bg-brand-subtle text-brand-deep" : tone === "success" ? "bg-[#149e6129] text-success-strong" : tone === "warning" ? "bg-amber-50 text-amber-700" : "bg-background text-muted"}`}><Icon size={19} /></span></div><p className="mt-5 text-2xl font-bold tracking-[-0.03em]">{value}</p><p className="mt-1 text-xs text-muted">{note}</p></article>)}</section>
    <section className="mt-6 grid gap-6 xl:grid-cols-[1.4fr_1fr]"><article className="ui-card overflow-hidden"><div className="flex items-center justify-between border-b border-border px-5 py-4"><div><h2 className="font-semibold">Vendas recentes</h2><p className="mt-1 text-xs text-muted">Últimos registros confirmados</p></div><Link href="/vendas" className="flex items-center gap-1 text-sm font-semibold text-brand-deep">Ver todas <ArrowRight size={16} /></Link></div>{data?.recentSales.length ? <ul className="divide-y divide-border">{data.recentSales.map((sale) => <li key={sale.id} className="grid gap-2 px-5 py-4 text-sm sm:grid-cols-[1fr_auto_auto] sm:items-center"><div><Link href={`/vendas/${sale.id}`} className="font-semibold hover:underline">{sale.number}</Link><p className="text-xs text-muted">{sale.source} · {data.pieceCount.get(sale.id) ?? 0} peça(s)</p></div><strong>{currency.format(Number(sale.total))}</strong><time className="text-xs text-muted">{sale.soldAt.toLocaleString("pt-BR")}</time></li>)}</ul> : <div className="px-6 py-14 text-center"><ShoppingBag className="mx-auto text-muted-soft" size={28} /><h3 className="mt-4 font-semibold">Nenhuma venda registrada</h3><p className="mt-1 text-sm text-muted">A primeira venda aparecerá aqui.</p></div>}</article><article className="ui-card p-6"><span className="grid size-10 place-items-center rounded-lg bg-brand-subtle text-brand-deep"><WalletCards size={20} /></span><p className="mt-7 text-sm text-muted">Financeiro</p><h2 className="mt-2 text-xl font-bold">Registros automáticos</h2><p className="mt-2 text-sm leading-6 text-muted">Vendas, recebimentos e lançamentos ficam organizados por data e hora.</p><Link href="/caixa" className="ui-button-primary mt-6">Ver movimentações<ArrowRight className="ml-2" size={17} /></Link></article></section>
  </>;
}
